### ISSUE TITLE
Adapter error messages

### ISSUE THREAD

**Issue by ck-coke** [arteck/ioBroker.bydbatt#1]
`
I'm getting these error messages in IOBroker log. What else can I check?
--
2021-01-06 19:51:51.595  - info: bydbatt.0 (23325) cleaned everything up...
2021-01-06 19:51:52.306  - info: bydbatt.0 (23325) terminating
2021-01-06 19:51:52.310  - info: bydbatt.0 (23325) Terminated (NO_ERROR): Without reason
2021-01-06 19:51:52.313  - info: bydbatt.0 (23325) terminating
2021-01-06 19:51:52.844  - info: host.smarthome instance system.adapter.bydbatt.0 terminated with code 0 (NO_ERROR)
2021-01-06 19:51:52.845  - info: host.smarthome Restart adapter system.adapter.bydbatt.0 because enabled
2021-01-06 19:52:22.878  - info: host.smarthome instance system.adapter.bydbatt.0 started with pid 23340
2021-01-06 19:52:25.288  - info: bydbatt.0 (23340) starting. Version 0.0.2 in /opt/iobroker/node_modules/iobroker.bydbatt, node: v14.15.1, js-controller: 3.1.6
2021-01-06 19:52:26.108  - error:  Unhandled promise rejection. This error originated either by throwing  inside of an async function without a catch block, or by rejecting a  promise which was not handled with .catch().
2021-01-06 19:52:26.109  - error: bydbatt.0 (23340) unhandled promise rejection: Request failed with status code 401
2021-01-06 19:52:26.112  - error: bydbatt.0 (23340) Error: Request failed with status code 401
at createError (/opt/iobroker/node_modules/@mhoc/axios-digest-auth/node_modules/axios/lib/core/createError.js:16:15)
at settle (/opt/iobroker/node_modules/@mhoc/axios-digest-auth/node_modules/axios/lib/core/settle.js:17:12)
at IncomingMessage.handleStreamEnd  (/opt/iobroker/node_modules/@mhoc/axios-digest-auth/node_modules/axios/lib/adapters/http.js:260:11)
at IncomingMessage.emit (events.js:327:22)
at endReadableNT (_stream_readable.js:1327:12)
at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-01-06 19:52:26.115  - info: bydbatt.0 (23340) cleaned everything up...
2021-01-06 19:52:26.683  - info: bydbatt.0 (23340) terminating
2021-01-06 19:52:26.687  - info: bydbatt.0 (23340) Terminated (NO_ERROR): Without reason
2021-01-06 19:52:26.693  - info: bydbatt.0 (23340) terminating
2021-01-06 19:52:27.217  - info: host.smarthome instance system.adapter.bydbatt.0 terminated with code 0 (NO_ERROR)
2021-01-06 19:52:27.218  - info: host.smarthome Restart adapter system.adapter.bydbatt.0 because enabled
2021-01-06 19:52:57.248  - info: host.smarthome instance system.adapter.bydbatt.0 started with pid 23357
2021-01-06 19:52:59.891  - info: bydbatt.0 (23357) starting. Version 0.0.2 in /opt/iobroker/node_modules/iobroker.bydbatt, node: v14.15.1, js-controller: 3.1.6
2021-01-06 19:53:00.451  - error:  Unhandled promise rejection. This error originated either by throwing  inside of an async function without a catch block, or by rejecting a  promise which was not handled with .catch().
2021-01-06 19:53:00.452  - error: bydbatt.0 (23357) unhandled promise rejection: Request failed with status code 401
2021-01-06 19:53:00.455  - error: bydbatt.0 (23357) Error: Request failed with status code 401
at createError (/opt/iobroker/node_modules/@mhoc/axios-digest-auth/node_modules/axios/lib/core/createError.js:16:15)
at settle (/opt/iobroker/node_modules/@mhoc/axios-digest-auth/node_modules/axios/lib/core/settle.js:17:12)
at IncomingMessage.handleStreamEnd  (/opt/iobroker/node_modules/@mhoc/axios-digest-auth/node_modules/axios/lib/adapters/http.js:260:11)
at IncomingMessage.emit (events.js:327:22)
at endReadableNT (_stream_readable.js:1327:12)
at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-01-06 19:53:00.457  - info: bydbatt.0 (23357) cleaned everything up...
2021-01-06 19:53:01.084  - info: bydbatt.0 (23357) terminating
2021-01-06 19:53:01.088  - info: bydbatt.0 (23357) Terminated (NO_ERROR): Without reason
2021-01-06 19:53:01.093  - info: bydbatt.0 (23357) terminating
2021-01-06 19:53:01.622  - info: host.smarthome instance system.adapter.bydbatt.0 terminated with code 0 (NO_ERROR)
2021-01-06 19:53:01.623  - info: host.smarthome Restart adapter system.adapter.bydbatt.0 because enabled

`

**Comment by arteck** [comment]
Error: Request failed with status code 401 

your side is not available

**Comment by ck-coke** [comment]
It is available. What else to check?

**Comment by arteck** [comment]
switch the adapter to debug .. i need the log

**Comment by ck-coke** [comment]
Found the problem. Username is not "user" but "installer". Maybe that should be added in the adapter config?
